[project]
name = "streamlit-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.43.2",
]

[tool.poe.tasks]
run = "streamlit run src/app/frontend/app.py"